  <div class="container">
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="index.php"><img src="img/logo.png"></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="index.php">Inicio <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Nosotros</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Modelos de Vehículos
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="index.php?categoria=1">Sedan</a>
                <a class="dropdown-item" href="index.php?categoria=2">SUV</a>
                <a class="dropdown-item" href="index.php?categoria=3">Camionetas</a>
                <a class="dropdown-item" href="index.php?categoria=4">Deportivos</a>
                <a class="dropdown-item" href="index.php?categoria=5">Buses</a>
                <a class="dropdown-item" href="index.php?categoria=6">Camiones</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="index.php">Ver todos</a>
              </div>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Contacto</a>
            </li>
          </ul>
          <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Buscar" aria-label="Search">
            <button class="btn btn-outline-danger my-2 my-sm-0" type="submit">Buscar vehículo</button>
          </form>
        </div>
      </nav>
    </div>